services:
  app:
    image: taller-api-rest:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tallerApiRest
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: UserDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ROOT
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Configura el email por defecto para pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin         # Configura la contraseña por defecto para pgAdmin
    ports:
      - "5050:80"

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

volumes:
  jenkins_home: