services:
  app:
    image: taller-api-rest:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/UserDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ROOT
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: UserDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ROOT
    ports:
      - "5432:5432"
    networks:
      - mynetwork


  dbLogs:
    image: postgres:13
    environment:
      POSTGRES_DB: logsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ROOT
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  logs:
    image: 1b867ae81b3ea2297c95ed3f19452116e4d3ff74274fd687a9949dd665e66d7b
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbLogs:5432/logsDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=ROOT
    ports:
      - "8002:8002" # Puerto para tu servicio de logs
    depends_on:
      - dbLogs
    networks:
      - mynetwork



  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Configura el email por defecto para pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin         # Configura la contraseña por defecto para pgAdmin
    ports:
      - "5050:80"
    networks:
      - mynetwork

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # RabbitMQ Management UI
    networks:
      - mynetwork



volumes:
  jenkins_home:

networks:
  mynetwork:
    driver: bridge